version: '3'
services:
  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      TZ: "Europe/Berlin"
    #command: --max_connections=1024
    tty: true

  phpmyadmin:
    container_name: phpmyadmin
    image: "phpmyadmin/phpmyadmin:latest"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: "mariadb"
      TZ: "Europe/Berlin"
    ports:
      - 3300:80
    tty: true
